
package telas;


import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.net.URL;
import javax.swing.*;
import paint.*;

/**
 *
 * @author trainee
 */
public class Launcher extends javax.swing.JFrame {

    private Integer valorLargura = 0;
    private Integer valorAltura = 0;
    private Integer valorDiametro = 0;
    private Integer valorLarguraSub = 0;
    private Integer valorAlturaSub = 0;
    private Integer valorDiametroSub = 0;
    private Integer posX;
    private Integer posY;
    private Desenho desenhar = new Desenho();
    private FuncoesInput input = new FuncoesInput();
    

    public JPanel getTela_de_desenho() {
        return tela;
    }

    public void setTela_de_desenho(JPanel tela_de_desenho) {
        this.tela = tela_de_desenho;
    }

   
    /**
     * Creates new form TelaPrincipal
     */
    public Launcher() {
       
        setIconImage(new ImageIcon("src/Icones/escova25x25.png").getImage());
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ToggleGroup = new javax.swing.ButtonGroup();
        menuMouseDireitoList = new javax.swing.JPopupMenu();
        editarMouse = new javax.swing.JMenu();
        mudarCorCorMenuMouse = new javax.swing.JMenuItem();
        mudarCorLinhaMenuMouse = new javax.swing.JMenuItem();
        ferramentasMenu = new javax.swing.JMenuItem();
        apagarMenu = new javax.swing.JMenuItem();
        ferramentas = new javax.swing.JDialog();
        labelDimensoes = new javax.swing.JLabel();
        labelLarguraMenu = new javax.swing.JLabel();
        labelAlturaMenu = new javax.swing.JLabel();
        labelMenuDiametro = new javax.swing.JLabel();
        inputLarguraMenu = new javax.swing.JTextField();
        inputAlturaMenu = new javax.swing.JTextField();
        labelPosição = new javax.swing.JLabel();
        labelPosiçãoXMenu = new javax.swing.JLabel();
        inputPosXMenu = new javax.swing.JTextField();
        labelPosiçãoYMenu = new javax.swing.JLabel();
        inputPosYMenu = new javax.swing.JTextField();
        inputDiametroMenu = new javax.swing.JTextField();
        salvarMenu = new javax.swing.JButton();
        telaAjuda = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        telaSair = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        botaoSair = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        armazem_de_tools = new javax.swing.JPanel();
        palette = new javax.swing.JButton();
        retangulo = new javax.swing.JToggleButton();
        circulo = new javax.swing.JToggleButton();
        triangulo = new javax.swing.JToggleButton();
        inputLargura = new javax.swing.JTextField();
        labelLargura = new javax.swing.JLabel();
        inputAltura = new javax.swing.JTextField();
        LabelAltura = new javax.swing.JLabel();
        inputDiametro = new javax.swing.JTextField();
        labelDiametro = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaObjetos = new javax.swing.JList<>();
        tela = new Panel(this.desenhar);
        menuBar = new javax.swing.JMenuBar();
        menuFIle = new javax.swing.JMenu();
        menuNovo = new javax.swing.JMenuItem();
        menuAbrir = new javax.swing.JMenuItem();
        menuSalvar = new javax.swing.JMenuItem();
        menuSalvarLimpar = new javax.swing.JMenuItem();
        menuRecentes = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuSair = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuRefazer = new javax.swing.JMenuItem();
        menuDesfazer = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        ajudaMenu = new javax.swing.JMenuItem();

        editarMouse.setText("Editar");

        mudarCorCorMenuMouse.setText("Cor: Corpo");
        mudarCorCorMenuMouse.setToolTipText("");
        mudarCorCorMenuMouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudarCorCorMenuMouseActionPerformed(evt);
            }
        });
        editarMouse.add(mudarCorCorMenuMouse);

        mudarCorLinhaMenuMouse.setText("Cor: Linha");
        mudarCorLinhaMenuMouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudarCorLinhaMenuMouseActionPerformed(evt);
            }
        });
        editarMouse.add(mudarCorLinhaMenuMouse);

        ferramentasMenu.setText("Ferramentas");
        ferramentasMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ferramentasMenuActionPerformed(evt);
            }
        });
        editarMouse.add(ferramentasMenu);

        menuMouseDireitoList.add(editarMouse);

        apagarMenu.setText("Apagar");
        apagarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarMenuActionPerformed(evt);
            }
        });
        menuMouseDireitoList.add(apagarMenu);

        ferramentas.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ferramentas.setTitle("Ferramentas");
        ferramentas.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        ferramentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ferramentas.setMaximumSize(new java.awt.Dimension(500, 250));
        ferramentas.setMinimumSize(new java.awt.Dimension(500, 250));
        ferramentas.setModalityType(java.awt.Dialog.ModalityType.TOOLKIT_MODAL);
        ferramentas.setResizable(false);
        ferramentas.setType(java.awt.Window.Type.UTILITY);

        labelDimensoes.setText("Dimensões:");

        labelLarguraMenu.setText("Largura:");

        labelAlturaMenu.setText("Altura:");

        labelMenuDiametro.setText("Diâmetro:");

        inputLarguraMenu.setEnabled(false);

        inputAlturaMenu.setEnabled(false);

        labelPosição.setText("Posição:");

        labelPosiçãoXMenu.setText("Posição X:");

        labelPosiçãoYMenu.setText("Posição Y:");

        inputDiametroMenu.setEnabled(false);

        salvarMenu.setText("Salvar");
        salvarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ferramentasLayout = new javax.swing.GroupLayout(ferramentas.getContentPane());
        ferramentas.getContentPane().setLayout(ferramentasLayout);
        ferramentasLayout.setHorizontalGroup(
            ferramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ferramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ferramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputLarguraMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputAlturaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLarguraMenu)
                    .addComponent(labelAlturaMenu)
                    .addComponent(labelMenuDiametro)
                    .addComponent(labelDimensoes)
                    .addComponent(inputDiametroMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(ferramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelPosição, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPosiçãoYMenu)
                    .addComponent(inputPosXMenu)
                    .addComponent(inputPosYMenu)
                    .addComponent(labelPosiçãoXMenu)
                    .addComponent(salvarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        ferramentasLayout.setVerticalGroup(
            ferramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ferramentasLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(ferramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDimensoes)
                    .addComponent(labelPosição))
                .addGap(24, 24, 24)
                .addGroup(ferramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLarguraMenu)
                    .addComponent(labelPosiçãoXMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ferramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputLarguraMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPosXMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ferramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlturaMenu)
                    .addComponent(labelPosiçãoYMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ferramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputAlturaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPosYMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(labelMenuDiametro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ferramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputDiametroMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salvarMenu))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        ferramentas.getAccessibleContext().setAccessibleDescription("");
        ferramentas.getAccessibleContext().setAccessibleParent(null);

        telaAjuda.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        telaAjuda.setMaximumSize(new java.awt.Dimension(377, 194));
        telaAjuda.setMinimumSize(new java.awt.Dimension(386, 135));
        telaAjuda.setResizable(false);
        telaAjuda.setSize(new java.awt.Dimension(386, 135));
        telaAjuda.setType(java.awt.Window.Type.UTILITY);

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jTextPane1.setText(" Para desenhar clique na figura que quiser, logo após isso coloque o valor numérico no campo requisitado pela figura. Assim, apenas clique na tela onde quiser e a figura com as medidas que colocou aparecerá. Caso queira editar o desenho, clique duas  vezes com o botão direito, na lista de figuras.");
        jTextPane1.setToolTipText("");
        jTextPane1.setOpaque(false);
        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout telaAjudaLayout = new javax.swing.GroupLayout(telaAjuda.getContentPane());
        telaAjuda.getContentPane().setLayout(telaAjudaLayout);
        telaAjudaLayout.setHorizontalGroup(
            telaAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaAjudaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        telaAjudaLayout.setVerticalGroup(
            telaAjudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        telaSair.setResizable(false);
        telaSair.setSize(new java.awt.Dimension(242, 110));
        telaSair.setType(java.awt.Window.Type.UTILITY);

        jLabel1.setText("Realmente deseja sair?");

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaSairLayout = new javax.swing.GroupLayout(telaSair.getContentPane());
        telaSair.getContentPane().setLayout(telaSairLayout);
        telaSairLayout.setHorizontalGroup(
            telaSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaSairLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telaSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaSairLayout.createSequentialGroup()
                        .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaSairLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        telaSairLayout.setVerticalGroup(
            telaSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaSairLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(telaSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSair)
                    .addComponent(botaoCancelar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paint");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setMinimumSize(new java.awt.Dimension(1086, 633));
        setName("MiniPaint"); // NOI18N
        setSize(new java.awt.Dimension(984, 633));

        armazem_de_tools.setBackground(new java.awt.Color(255, 255, 255));
        armazem_de_tools.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        armazem_de_tools.setToolTipText("");
        armazem_de_tools.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        palette.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/paleta64x64.png"))); // NOI18N
        palette.setToolTipText("Paleta de cores");
        palette.setBorderPainted(false);
        palette.setContentAreaFilled(false);
        palette.setFocusPainted(false);
        palette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paletteActionPerformed(evt);
            }
        });

        ToggleGroup.add(retangulo);
        retangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/rectangle 64x64.png"))); // NOI18N
        retangulo.setToolTipText("Desenhar retângulos");
        retangulo.setBorderPainted(false);
        retangulo.setContentAreaFilled(false);
        retangulo.setFocusPainted(false);
        retangulo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/retanguloSelected64x64.png"))); // NOI18N
        retangulo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/retanguloSelected64x64.png"))); // NOI18N
        retangulo.setVerifyInputWhenFocusTarget(false);
        retangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retanguloActionPerformed(evt);
            }
        });

        ToggleGroup.add(circulo);
        circulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/circle 64x64.png"))); // NOI18N
        circulo.setToolTipText("Desenhar círculos");
        circulo.setBorderPainted(false);
        circulo.setContentAreaFilled(false);
        circulo.setFocusPainted(false);
        circulo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/circuloSelected64x64.png"))); // NOI18N
        circulo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/circuloSelected64x64.png"))); // NOI18N
        circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circuloActionPerformed(evt);
            }
        });

        ToggleGroup.add(triangulo);
        triangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/triangulo 64x64.png"))); // NOI18N
        triangulo.setToolTipText("Desenhar triângulos");
        triangulo.setBorderPainted(false);
        triangulo.setContentAreaFilled(false);
        triangulo.setFocusPainted(false);
        triangulo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/trianguloSelected64x64.png"))); // NOI18N
        triangulo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/trianguloSelected64x64.png"))); // NOI18N
        triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trianguloActionPerformed(evt);
            }
        });

        inputLargura.setEditable(false);
        inputLargura.setText("0");
        inputLargura.setToolTipText("Largura da figura");
        inputLargura.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelLargura.setText("Largura:");
        labelLargura.setToolTipText("Largura do desenho");
        labelLargura.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        inputAltura.setEditable(false);
        inputAltura.setText("0");
        inputAltura.setToolTipText("Altura da figura"); // NOI18N
        inputAltura.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LabelAltura.setText("Altura:");
        LabelAltura.setToolTipText("Altura do desenho");
        LabelAltura.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        inputDiametro.setEditable(false);
        inputDiametro.setText("0");
        inputDiametro.setToolTipText("Diâmetro do círculo");
        inputDiametro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelDiametro.setText("Diâmetro:");
        labelDiametro.setToolTipText("Diâmetro do círculo");

        ToggleGroup.add(jToggleButton1);
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/caneta64x64.png"))); // NOI18N
        jToggleButton1.setToolTipText("Desenho livre(desabilitado)");
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.setFocusPainted(false);
        jToggleButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/canetaSelected64x64.png"))); // NOI18N
        jToggleButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/canetaSelected64x64.png"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout armazem_de_toolsLayout = new javax.swing.GroupLayout(armazem_de_tools);
        armazem_de_tools.setLayout(armazem_de_toolsLayout);
        armazem_de_toolsLayout.setHorizontalGroup(
            armazem_de_toolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(palette, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(retangulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(circulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(triangulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(armazem_de_toolsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(armazem_de_toolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputLargura)
                    .addComponent(labelLargura)
                    .addComponent(inputAltura)
                    .addComponent(LabelAltura)
                    .addComponent(inputDiametro)
                    .addComponent(labelDiametro))
                .addGap(15, 15, 15))
            .addComponent(jToggleButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        armazem_de_toolsLayout.setVerticalGroup(
            armazem_de_toolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(armazem_de_toolsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelLargura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelAltura)
                .addGap(5, 5, 5)
                .addComponent(inputAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelDiametro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputDiametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(palette)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(retangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(circulo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(triangulo)
                .addGap(34, 34, 34))
        );

        listaObjetos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        listaObjetos.setToolTipText("Seleção da figura");
        listaObjetos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listaObjetos.setName(""); // NOI18N
        listaObjetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaObjetosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaObjetos);

        tela.setBackground(new java.awt.Color(255, 255, 255));
        tela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tela.setToolTipText("Área de desenho");
        tela.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        tela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout telaLayout = new javax.swing.GroupLayout(tela);
        tela.setLayout(telaLayout);
        telaLayout.setHorizontalGroup(
            telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );
        telaLayout.setVerticalGroup(
            telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        menuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBar.setFocusCycleRoot(true);

        menuFIle.setText("Arquivos");

        menuNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Novo 16x16.png"))); // NOI18N
        menuNovo.setText(" Novo");
        menuNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoActionPerformed(evt);
            }
        });
        menuFIle.add(menuNovo);

        menuAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menuAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Abrir 16x16.png"))); // NOI18N
        menuAbrir.setText(" Abrir");
        menuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbrirActionPerformed(evt);
            }
        });
        menuFIle.add(menuAbrir);

        menuSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        menuSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Salvar como 16x16.png"))); // NOI18N
        menuSalvar.setText(" Salvar");
        menuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalvarActionPerformed(evt);
            }
        });
        menuFIle.add(menuSalvar);

        menuSalvarLimpar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuSalvarLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Salvar 16x16.png"))); // NOI18N
        menuSalvarLimpar.setText(" Salvar e limpar");
        menuSalvarLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalvarLimparActionPerformed(evt);
            }
        });
        menuFIle.add(menuSalvarLimpar);

        menuRecentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Recentes 16x16.png"))); // NOI18N
        menuRecentes.setText(" Recentes");
        menuFIle.add(menuRecentes);
        menuFIle.add(jSeparator1);

        menuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Sair 16x16.png"))); // NOI18N
        menuSair.setText(" Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuFIle.add(menuSair);

        menuBar.add(menuFIle);
        menuFIle.getAccessibleContext().setAccessibleParent(tela);

        menuEdit.setText("Edit");

        menuRefazer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        menuRefazer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/refazer16x16.png"))); // NOI18N
        menuRefazer.setText("Refazer");
        menuEdit.add(menuRefazer);

        menuDesfazer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        menuDesfazer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/desfazer16x16.png"))); // NOI18N
        menuDesfazer.setText("Desfazer");
        menuEdit.add(menuDesfazer);
        menuEdit.add(jSeparator2);

        ajudaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/ajuda16x16.png"))); // NOI18N
        ajudaMenu.setText("Ajuda");
        ajudaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajudaMenuActionPerformed(evt);
            }
        });
        menuEdit.add(ajudaMenu);

        menuBar.add(menuEdit);
        menuEdit.getAccessibleContext().setAccessibleParent(tela);

        setJMenuBar(menuBar);
        menuBar.getAccessibleContext().setAccessibleParent(tela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(armazem_de_tools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(armazem_de_tools, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Métodos Getters e Setters
    public Integer getValorLargura() {
        return valorLargura;
    }

    public void setValorLargura(Integer valorLargura) {
        this.valorLargura = valorLargura;
    }

    public Integer getValorAltura() {
        return valorAltura;
    }

    public void setValorAltura(Integer valorAltura) {
        this.valorAltura = valorAltura;
    }

    public Integer getValorDiametro() {
        return valorDiametro;
    }

    public void setValorDiametro(Integer valorDiametro) {
        this.valorDiametro = valorDiametro;
    }
    
    private void menuNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoActionPerformed
        // Limpa a tela
        desenhar.rmTela(tela, listaObjetos);
        
    }//GEN-LAST:event_menuNovoActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        // Abre a tela de confirmação de saída
        telaSair.setLocationRelativeTo(tela);
        telaSair.setVisible(true);
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirActionPerformed
        // Carrega o arquivo salvo na tela
        desenhar.carregarArquivo(this.tela, tela.getGraphics(), this.listaObjetos);
    }//GEN-LAST:event_menuAbrirActionPerformed

    private void menuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalvarActionPerformed
        // Salva o arquivo
        desenhar.salvarArquivo(this.tela);
    }//GEN-LAST:event_menuSalvarActionPerformed

    private void retanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retanguloActionPerformed
        //Ativa o desenho dos retângulos e modificar as propriedades do input  
        this.valorDiametro = 0;
        this.valorAltura = 0;
        this.valorLargura = 0;
        inputDiametro.setEditable(false);
        inputDiametro.setText("0");
        inputLargura.setText("0");
        inputAltura.setText("0");
        inputAltura.setEditable(true);
        inputLargura.setEditable(true);
        this.desenhar.setControle(1);
       
    }//GEN-LAST:event_retanguloActionPerformed

    private void paletteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paletteActionPerformed
        // Abre as opções de cores 
        Color paleta = JColorChooser.showDialog(null, "Paleta", getForeground());
      
        if(paleta != null){
            desenhar.setFill(true);
            desenhar.setCor(paleta);
        }
       
    }//GEN-LAST:event_paletteActionPerformed

    private void circuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circuloActionPerformed
        //Ativa o desenho dos círculos e modificar as propriedades do input  
        this.valorDiametro = 0;
        this.valorAltura = 0;
        this.valorLargura = 0;
        inputAltura.setEditable(false);
        inputLargura.setEditable(false);
        inputAltura.setText("0");
        inputLargura.setText("0");
        inputDiametro.setEditable(true);
        this.desenhar.setControle(2);   
    }//GEN-LAST:event_circuloActionPerformed
   
    private void listaObjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaObjetosMouseClicked
        // Ativa o menu de opções para modificar as propriedas dos desenhos
        if(evt.getClickCount() == 2){
            if(SwingUtilities.isLeftMouseButton(evt)){
                menuMouseDireitoList.show(listaObjetos, evt.getX(), evt.getY());
            }
        }  
       
    }//GEN-LAST:event_listaObjetosMouseClicked

    private void apagarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarMenuActionPerformed
        // Deleta um desenho
        try{
            desenhar.rmForma(tela, tela.getGraphics(), listaObjetos, listaObjetos.getSelectedIndex());
        }
        catch(ArrayIndexOutOfBoundsException error){
            JOptionPane.showMessageDialog(this, "Selecione uma figura!", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_apagarMenuActionPerformed

    private void menuSalvarLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalvarLimparActionPerformed
        // Salva o arquivo e limpa a tela
        desenhar.salvarArquivo(tela);
        desenhar.rmTela(tela, listaObjetos);
       
    }//GEN-LAST:event_menuSalvarLimparActionPerformed

    private void mudarCorCorMenuMouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudarCorCorMenuMouseActionPerformed
        // Modifica a cor do desenho
        try{
            Color paleta = JColorChooser.showDialog(null, "Paleta", getForeground());
            desenhar.alterarCor(tela, tela.getGraphics(), listaObjetos.getSelectedIndex(), paleta);
        }    
        catch(ArrayIndexOutOfBoundsException error){
            JOptionPane.showMessageDialog(this, "Selecione uma figura!", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_mudarCorCorMenuMouseActionPerformed

    private void ferramentasMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ferramentasMenuActionPerformed
        // Define os valores nas caixas dialogo, e abre a tela
        try{
            this.valorDiametroSub = 0;
            this.valorAlturaSub = 0;
            this.valorLarguraSub = 0;
            int index = listaObjetos.getSelectedIndex();


            if(desenhar.getFiguras().get(listaObjetos.getSelectedIndex()) instanceof Rectangle){
                Rectangle retangulo = (Rectangle)desenhar.getFiguras().get(index);
                String largura = Integer.toString(retangulo.getLargura());
                String altura = Integer.toString(retangulo.getAltura());
                String posX = Integer.toString(retangulo.getX());
                String posY = Integer.toString(retangulo.getY());
                this.posX = retangulo.getX();
                this.posY = retangulo.getY();
                this.valorLarguraSub = retangulo.getLargura();
                this.valorAlturaSub = retangulo.getAltura();
                inputPosXMenu.setText(posX);
                inputPosYMenu.setText(posY);
                inputDiametroMenu.setText("0");
                inputLarguraMenu.setText(largura);
                inputAlturaMenu.setText(altura);
                inputDiametroMenu.setEnabled(false);
                inputAlturaMenu.setEnabled(true);
                inputLarguraMenu.setEnabled(true);
            }

            else if(desenhar.getFiguras().get(listaObjetos.getSelectedIndex()) instanceof Triangle){
                Triangle triangulo = (Triangle)desenhar.getFiguras().get(index);
                String largura = Integer.toString(triangulo.getLargura());
                String altura = Integer.toString(triangulo.getAltura());
                String posX = Integer.toString(retangulo.getX());
                String posY = Integer.toString(retangulo.getY());
                this.posX = triangulo.getX();
                this.posY = triangulo.getY();
                this.valorLarguraSub = triangulo.getLargura();
                this.valorAlturaSub = triangulo.getAltura();
                inputPosXMenu.setText(posX);
                inputPosYMenu.setText(posY);
                inputDiametroMenu.setText("0");
                inputLarguraMenu.setText(largura);
                inputAlturaMenu.setText(altura);
                inputDiametroMenu.setEnabled(false);
                inputAlturaMenu.setEnabled(true);
                inputLarguraMenu.setEnabled(true);
            }

            else if(desenhar.getFiguras().get(listaObjetos.getSelectedIndex()) instanceof Circle){
                Circle circulo = (Circle)desenhar.getFiguras().get(index);
                String diametro = Integer.toString(circulo.getDiametro());
                String posX = Integer.toString(retangulo.getX());
                String posY = Integer.toString(retangulo.getY());
                this.posX = circulo.getX();
                this.posY = circulo.getY();
                this.valorDiametroSub = circulo.getDiametro();
                inputPosXMenu.setText(posX);
                inputPosYMenu.setText(posY);
                inputLarguraMenu.setText("0");
                inputAlturaMenu.setText("0");
                inputDiametroMenu.setText(diametro);
                inputAlturaMenu.setEnabled(false);
                inputLarguraMenu.setEnabled(false);
                inputDiametroMenu.setEnabled(true);
            }

            ferramentas.setLocationRelativeTo(tela);
            ferramentas.setVisible(true);
        }
        catch(ArrayIndexOutOfBoundsException error){
            JOptionPane.showMessageDialog(this, "Selecione uma figura!", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ferramentasMenuActionPerformed

    private void salvarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarMenuActionPerformed
        // Modifica os atributos das figuras
        this.valorLarguraSub = input.inputValor(this, ferramentas, inputLarguraMenu);
        this.valorAlturaSub = input.inputValor(this, ferramentas, inputAlturaMenu);
        this.valorDiametroSub = input.inputValor(this, ferramentas, inputDiametroMenu);
        this.posY = input.inputPos(ferramentas, inputPosYMenu);
        this.posX = input.inputPos(ferramentas, inputPosXMenu);
        ferramentas.dispose();
        desenhar.movimentarFigura(tela, tela.getGraphics(), listaObjetos.getSelectedIndex(), this.posX, this.posY);
        desenhar.redimensionarFigura(tela, tela.getGraphics(), listaObjetos.getSelectedIndex(), this.valorLarguraSub, this.valorAlturaSub, this.valorDiametroSub);
        
        
    }//GEN-LAST:event_salvarMenuActionPerformed

    private void mudarCorLinhaMenuMouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudarCorLinhaMenuMouseActionPerformed
        // Modifica a cor da linha da figura
        try{
            Color paleta = JColorChooser.showDialog(null, "Paleta", getForeground());
            desenhar.alterarCorBorda(tela, tela.getGraphics(), listaObjetos.getSelectedIndex(), paleta);
        }
        catch(ArrayIndexOutOfBoundsException error){
            JOptionPane.showMessageDialog(this, "Selecione uma figura!", "Aviso", JOptionPane.WARNING_MESSAGE);
        }    
       
    }//GEN-LAST:event_mudarCorLinhaMenuMouseActionPerformed

    private void trianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trianguloActionPerformed
        //Ativa o desenho dos triângulos e modificar as propriedades do input
        this.valorDiametro = 0;
        this.valorAltura = 0;
        this.valorLargura = 0;
        inputDiametro.setEditable(false);
        inputDiametro.setText("0");
        inputLargura.setText("0");
        inputAltura.setText("0");
        inputAltura.setEditable(true);
        inputLargura.setEditable(true);
        this.desenhar.setControle(3);
    }//GEN-LAST:event_trianguloActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void telaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telaMouseClicked
        // Realiza o desenho na tela
        Form desenho;
       
        // Recebe os valores digitados nas caixas
        this.valorLargura = input.inputValor(this, ferramentas, this.inputLargura);
        this.valorAltura = input.inputValor(this, ferramentas, this.inputAltura);
        this.valorDiametro = input.inputValor(this, ferramentas, this.inputDiametro);
        // Desenha ao clicar com o botão direito do mouse
        if(SwingUtilities.isLeftMouseButton(evt)){
            // Irá desenhar um retângulo
            if(desenhar.getControle() == 1){

                this.desenhar.setLargura(this.valorLargura);
                this.desenhar.setAltura(this.valorAltura);
                desenho = desenhar.criarFigura(evt, listaObjetos);
                try{
                    if(this.valorAltura == 0 || this.valorLargura == 0){
                        throw new NumberFormatException();
                    }
                    desenho.desenhar(tela.getGraphics());

                }
                catch(NumberFormatException error){
                     
                    JOptionPane.showMessageDialog(this, "Valor vazio!", "ERROR", JOptionPane.WARNING_MESSAGE);
                }
            }
            
            // Irá desenhar um círculo
            else if(desenhar.getControle() == 2){
                this.desenhar.setDiametro(this.valorDiametro);
                desenho = desenhar.criarFigura(evt, listaObjetos);
                try{
                    if(this.valorDiametro == 0){
                        throw new NumberFormatException();
                    }
                    desenho.desenhar(tela.getGraphics());
                }
                catch (NumberFormatException error){
                    
                    JOptionPane.showMessageDialog(this, "Valor vazio!", "ERROR", JOptionPane.WARNING_MESSAGE);
                }

            }

            // Irá desenhar um triângulo
            else if(desenhar.getControle() == 3){
                this.desenhar.setLargura(this.valorLargura);
                this.desenhar.setAltura(this.valorAltura);
                desenho = desenhar.criarFigura(evt, listaObjetos);
                try{  
                    if(this.valorAltura == 0 || this.valorLargura == 0){
                        throw new NumberFormatException();
                    }
                    desenho.desenhar(tela.getGraphics());              
                }
                catch(NumberFormatException error){
                    
                    JOptionPane.showMessageDialog(this, "Valor vazio!", "ERROR", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
      
       
       
    }//GEN-LAST:event_telaMouseClicked

    private void ajudaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajudaMenuActionPerformed
        // Abre a tela de ajuda
        telaAjuda.setLocationRelativeTo(tela);
        telaAjuda.setVisible(true);
       
    }//GEN-LAST:event_ajudaMenuActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        // Encerra a aplicação
        System.exit(0);
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        // Fecha a tela de confirmação de saída
        telaSair.dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                Launcher launcher = new Launcher();
                
                launcher.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAltura;
    private javax.swing.ButtonGroup ToggleGroup;
    private javax.swing.JMenuItem ajudaMenu;
    private javax.swing.JMenuItem apagarMenu;
    private javax.swing.JPanel armazem_de_tools;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoSair;
    private javax.swing.JToggleButton circulo;
    private javax.swing.JMenu editarMouse;
    private javax.swing.JDialog ferramentas;
    private javax.swing.JMenuItem ferramentasMenu;
    private javax.swing.JTextField inputAltura;
    private javax.swing.JTextField inputAlturaMenu;
    private javax.swing.JTextField inputDiametro;
    private javax.swing.JTextField inputDiametroMenu;
    private javax.swing.JTextField inputLargura;
    private javax.swing.JTextField inputLarguraMenu;
    private javax.swing.JTextField inputPosXMenu;
    private javax.swing.JTextField inputPosYMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel labelAlturaMenu;
    private javax.swing.JLabel labelDiametro;
    private javax.swing.JLabel labelDimensoes;
    private javax.swing.JLabel labelLargura;
    private javax.swing.JLabel labelLarguraMenu;
    private javax.swing.JLabel labelMenuDiametro;
    private javax.swing.JLabel labelPosição;
    private javax.swing.JLabel labelPosiçãoXMenu;
    private javax.swing.JLabel labelPosiçãoYMenu;
    private javax.swing.JList<String> listaObjetos;
    private javax.swing.JMenuItem menuAbrir;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuDesfazer;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFIle;
    private javax.swing.JPopupMenu menuMouseDireitoList;
    private javax.swing.JMenuItem menuNovo;
    private javax.swing.JMenuItem menuRecentes;
    private javax.swing.JMenuItem menuRefazer;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem menuSalvar;
    private javax.swing.JMenuItem menuSalvarLimpar;
    private javax.swing.JMenuItem mudarCorCorMenuMouse;
    private javax.swing.JMenuItem mudarCorLinhaMenuMouse;
    private javax.swing.JButton palette;
    private javax.swing.JToggleButton retangulo;
    private javax.swing.JButton salvarMenu;
    private javax.swing.JPanel tela;
    private javax.swing.JDialog telaAjuda;
    private javax.swing.JDialog telaSair;
    private javax.swing.JToggleButton triangulo;
    // End of variables declaration//GEN-END:variables
    
  
}
